### ISSUE TITLE
[Discussion] Environment or some other better name?

### ISSUE THREAD

**Issue by resouer** [cloud-native-application/RudrX#110]
Environment is an abstraction for developing/staging/production environment of the app. In practice, it could be a combination of Kubernetes Namespace, Service Account and RBAC, for example: https://github.com/stefanprodan/podinfo/tree/master/deploy/webapp/common

While the drawback of this name is it kind conflicts with `env` in Kubernetes Deployment.

So not sure there's other better name for this?

**Comment by wonderflow** [comment]
I think it doesn't matter, users will easily understand they are different.  Can we close it? @resouer
