### ISSUE TITLE
[DISCUSSION] Should we emphasize the chart release name?

### ISSUE THREAD

**Issue by zzxwill** [cloud-native-application/RudrX#126]
We clearly displayed the release name `core-runtime` for OAM-Kubernetes-runtime, but we don't use later. So how about not displaying it, or renaming it to `oam-kubernetes-runtime`. 

BTW, what's the expected output for `Versions`?

```
[root@iZj6cc54ecpc3pm8t9yctuZ Rudrx]# vela system:init
"crossplane-master" has been added to your repositories
Successfully installed oam-kubernetes-runtime release:  core-runtime

[root@iZj6cc54ecpc3pm8t9yctuZ Rudrx]# vela system:info
Versions:
oam-kubernetes-runtime: 0.0.8-17.g269dc30
```

**Comment by resouer** [comment]
@zzxwill  renaming it to oam-kubernetes-runtime  sounds good

**Comment by wonderflow** [comment]
closing as we will build vela core including oam-k8s-runtime, this won't be an issue now. I will be called `vela-core` if we still using helm
