### ISSUE TITLE
[Feature][Dashboard] Design/Implement Env management (env add/delete/list)

### ISSUE THREAD

**Issue by zzxwill** [cloud-native-application/RudrX#190]
Currently in Vela Dashboard, env list and switch is available, while env add/delete/list (with namespace information) need to be designed and implemented.

For the complete env features, please refer to https://github.com/cloud-native-application/RudrX/blob/master/documentation/vela.md with keyword `env`.

**Comment by wenxinnnnn** [comment]
Please assign it to me!

**Comment by wenxinnnnn** [comment]
Closed it as it has been merged in #230
