### ISSUE TITLE
[feature] Add Docker Compose support

### ISSUE THREAD

**Issue by resouer** [cloud-native-application/RudrX#29]
Docker Compose seamless works with OAM primitives, we should consider support a Compose style `rudrxFile` at day 0 or day 1.

![image](https://user-images.githubusercontent.com/1701782/87839757-1517aa00-c851-11ea-81ce-4f4266675b62.png)

**Comment by wonderflow** [comment]
supported like this https://github.com/cloud-native-application/RudrX/blob/master/pkg/cue/testdata/apps/myapp.yaml
in #86
