### ISSUE TITLE
[feature] Can we use --link to model multiple components?

### ISSUE THREAD

**Issue by resouer** [cloud-native-application/RudrX#30]
For now, we only support one Component one AppConfig, it should work.

Though, we could have a way to model multiple Components in same AppConfig in a "link" approach.

```console
$ rudr run stateful mysql mysql:5.1
$ rudr run deployment frontend -p 80 --link mysql nginx:1.9.4
```
In this case, app engine will add frontend to the existing mysql AppConfig. Nothing else needed. /cc @wonderflow 

xref: https://docs.docker.com/compose/compose-file/#links

**Comment by wonderflow** [comment]
Now every workload (OAM component) is an app, and we use `--app <bundle>` to bundle a set of app, this was implemented by #145
