### ISSUE TITLE
Prettify usage

### ISSUE THREAD

**Issue by erdun** [cloud-native-application/RudrX#64]
Rudrx should be friendly to the end-users, and there are two points we should do

* showing all global flags controller-runtime client need in a clean way
* classify commands like `kubectl` or `istioctl`

**Comment by zzxwill** [comment]
> * showing all global flags controller-runtime client need in a clean way

I think we need to hide those client flags as it will be simple for rudrx itself to be only depended on `kubeconfig`.

> * classify commands like `kubectl` or `istioctl`

+1

**Comment by wonderflow** [comment]
fixed by #107
