### ISSUE TITLE
[Feature] show currently using env

### ISSUE THREAD

**Issue by zzxwill** [cloud-native-application/RudrX#81]
Provide a way to show currently using env.

Or mark the currently using one in the list.
```
✗ rudr env
NAME     	NAMESPACE
default  	default
env-hello（*current*）	env-hello
env-world	default
test     	test
```

**Comment by zzxwill** [comment]
The user might forget which env he/she switched to after he/she returned from a cup of coffee.

**Comment by wonderflow** [comment]
Good idea！
