### ISSUE TITLE
[Discussion] Using github repo as addon/capability might hit `API rate limit exceeded` issue

### ISSUE THREAD

**Issue by zzxwill** [cloud-native-application/RudrX#97]
Per PR https://github.com/cloud-native-application/RudrX/pull/96, I hit an issue as below for a specified IP.
`{"message":"API rate limit exceeded for 47.251.34.248. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}`

The [official doc](https://developer.github.com/v3/#rate-limiting) says.
`For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.`

**Comment by wonderflow** [comment]
you may mock the API for test

**Comment by zzxwill** [comment]
@wonderflow You are right. But for production, users might hit the issue.
